Algoritmo "Corte de funcionários"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/08/2026
Var
Nome,Setor:caracter
Salario:real

Inicio
EscrevaL("Digite o seu nome")
Leia(Nome)
EscrevaL("Digite o seu setor")
Leia(Setor)
Escreva("Digite o seu salário R$")
Leia(Salario)
se Salario>5000 Então
   Escreval("Demitido")
    senao
     Escreval("Permanece")
fimse
Fimalgoritmo