Algoritmo "Criança Esperança"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/09/2026
Var
valor:inteiro
Inicio
Escreval("*** DOAÇÃO CRIANÇA ESPERANÇA ***")
Escreval("")
Escreval("Digite 1 para doar R$10,00")
Escreval("Digite 2 para doar R$20,00")
Escreval("Digite 3 para doar R$40,00")
Escreval("Digite 4 para doar R$80,00")
Escreval("Digite 5 para doar outro valor")
Leia(valor)
Escolha valor
        caso 1
        Escreval("vc doou R$10,00")
        caso 2
        Escreval("vc doou R$20,00")
        caso 3
        Escreval("vc doou R$40,00")
        caso 4
        Escreval("vc doou R$80,00")
        caso 5
        Escreval("Digite o valor a ser doado:")
        Leia(valor)
fimescolha
Fimalgoritmo