Algoritmo "Hotel Fazenda"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/09/2026
Var
Cliente:caracter
Quartos,dias,formapag:inteiro
diária1,diária2,diária3,desc,totpag,total,subtotal,gasts_add:real
Inicio
desc<-10/100
diária1<-80
diária2<-100
diária3<-180
subtotal<-0
totpag<-0
total<-0
Fimalgoritmo